trigger:
- master

pool:
 name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd 01-login
    npm cache clean --force
    npm install
    npm start
  displayName: 'npm install and build'
