trigger:
- master

pool:
 name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd 01-login
    npm install
    npm run build
  displayName: 'npm install and build'
