trigger:
- master

pool:
 name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '10.x'
    checkLatest: true
    force32bit: true
  displayName: 'Install Node.js'

- script: |
    cd 01-login
    npm install
    npm run build
  displayName: 'npm install and build'
